app:
  port: 8688

database:
  driver: mysql
  host: localhost
  port: 3306
  username: root
  password: "5211314."
  name: firewall-manager
  charset: utf8mb4
  loc: Local
  parse_time: true

log:
  level: info
  format: json  
  log_dir: logs
  show_line: true
  log_in_console: false
  max_size: 100
  max_backups: 7
  max_age: 30
  compress: true