app:
  port: 8688

log:
  level: info
  format: json  
  log_dir: logs
  show_line: true
  log_in_console: false
  max_size: 100
  max_backups: 7
  max_age: 30
  compress: true

firewall_type: iptables